/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spond.club.api;

import com.spond.club.api.model.ApiError;
import com.spond.club.api.model.PublicSignupForm;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-02T13:42:36.360657+02:00[Europe/Oslo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "SignupForms", description = "the SignupForms API")
public interface SignupFormsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/forms/{formId} : Get public signup form details
     *
     * @param formId Public identifier for the signup form. (required)
     * @return Public signup form details (status code 200)
     *         or Form not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getSignupForm",
        summary = "Get public signup form details",
        tags = { "SignupForms" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Public signup form details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PublicSignupForm.class))
            }),
            @ApiResponse(responseCode = "404", description = "Form not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/forms/{formId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PublicSignupForm> getSignupForm(
        @Parameter(name = "formId", description = "Public identifier for the signup form.", required = true, in = ParameterIn.PATH) @PathVariable("formId") String formId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"formId\" : \"B171388180BC457D9887AD92B6CCFC86\", \"clubId\" : \"britsport\", \"memberTypes\" : [ { \"name\" : \"Active Member\", \"id\" : \"8FE4113D4E4020E0DCF887803A886981\" }, { \"name\" : \"Active Member\", \"id\" : \"8FE4113D4E4020E0DCF887803A886981\" } ], \"registrationOpens\" : \"2024-12-16T00:00:00Z\", \"title\" : \"Coding camp summer 2025\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"Form not found\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"Form not found\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
