/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spond.club.api;

import com.spond.club.api.model.ApiError;
import com.spond.club.api.model.CreateRegistrationRequest;
import com.spond.club.api.model.RegistrationSubmissionResponse;
import com.spond.club.api.model.ValidationError;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;

import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-02T13:42:36.360657+02:00[Europe/Oslo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "SignupRegistrations", description = "the SignupRegistrations API")
public interface SignupRegistrationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/forms/{formId}/submissions : Submit a club signup registration
     *
     * @param formId Public identifier for the signup form. (required)
     * @param createRegistrationRequest  (required)
     * @return Registration submitted successfully (status code 201)
     *         or Invalid request payload (status code 400)
     *         or Form not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "submitSignupForm",
        summary = "Submit a club signup registration",
        tags = { "SignupRegistrations" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Registration submitted successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RegistrationSubmissionResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request payload", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Form not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/forms/{formId}/submissions",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<RegistrationSubmissionResponse> submitSignupForm(
        @Parameter(name = "formId", description = "Public identifier for the signup form.", required = true, in = ParameterIn.PATH) @PathVariable("formId") String formId,
        @Parameter(name = "CreateRegistrationRequest", description = "", required = true) @Valid @RequestBody CreateRegistrationRequest createRegistrationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"formId\" : \"B171388180BC457D9887AD92B6CCFC86\", \"submitted\" : true, \"message\" : \"Registration submitted successfully.\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fieldErrors\" : [ { \"field\" : \"email\", \"message\" : \"must be a valid email address\" }, { \"field\" : \"email\", \"message\" : \"must be a valid email address\" } ], \"message\" : \"Validation failed\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"Form not found\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"Form not found\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
